### ISSUE TITLE
Cucumber Archtype import cleanup

### ISSUE THREAD

**Issue by eskape** [serenity-bdd/serenity-maven-archetypes#1]
Hi!

We use the archtype to bootstrap several teams with Serenity.
But the cucumber-archtype contains deprecated annotations (like old thucydides FindBy and WebElementFacade). Want to get rid of them by using the proper ones.

I have the changes for the archetype on my machine (including unused imports cleanup). Shall I send them? Pull request?

**Comment by wakaleo** [comment]
Certainly, pull requests are always welcome!

**Comment by eskape** [comment]
When are you going to release the archetype?

**Comment by eskape** [comment]
thanks for releasing!
